### ISSUE TITLE
Extend user interface to query decompositions that use a given class

### ISSUE THREAD

**Issue by nichtich** [gbv/coli-ana#21]
With #20 the api supports an alternative query parameter. The user interface needs to be extended to support browsing decompositions via their members.

**Comment by stefandesu** [comment]
Any specific ideas on the implementation? We could definitely reuse the Analyze.vue component and make it aware of the two options. When searching via members, those members should be highlighted in the results.

**Comment by nichtich** [comment]
* [ ] One input field, two buttons, e.g. "analyze" and "lookup"
* [ ] When searching via members, those members should be highlighted in the results
* [ ] pagination for large result sets

A more sophisticated interface might make sense for browsing the hierarchy enriched with composed classes but this is another issue and possible better located in Cocoda.

**Comment by stefandesu** [comment]
Okay, I'll give it a try later.

**Comment by stefandesu** [comment]
First implementation is now pushed to dev:
- `lookup` button is implemented next to analyze
- `analyze` is still the default (i.e. when pressing enter in the text field)
- member is highlighted in results (currently in blue, but we can change the color; note that we have to use a color because bold means something else and italic might not be obvious)
- currently no pagination (displayed results are capped at 10 for now)
- currently nothing is displayed if there are no results for a lookup; there should be something

**Comment by nichtich** [comment]
> currently nothing is displayed if there are no results for a lookup; there should be something

How about like "No decomposition found for:" but "Not found as part of any analysis:"?

**Comment by nichtich** [comment]
Adding a way to click on a member to perform a query would allow to browse around in the analysis. Maybe make the notation linked to an lookup query with this member and hover in blue?

**Comment by stefandesu** [comment]
I'm not sure if I completely understand how you imagine it, but I think it would be very irritating if a click on a member performed a completely different query and removed all your current results. You talk about "brows[ing] around in the analysis", but that's not how I imagine browsing to work. So maybe you could describe in more detail how you imagine it?

My suggestion would be to have a button in the popover, just like the open in Cocoda button, for every member.

Also, one unrelated question: Should we allow searching for multiple members at the same time? Currently, you can only search for one member. And if yes, should it be OR or AND? Both kind of make sense, so maybe we need another option...

**Comment by nichtich** [comment]
> My suggestion would be to have a button in the popover, just like the open in Cocoda button, for every member.

ok!

> Currently, you can only search for one member. And if yes, should it be OR or AND? Both kind of make sense, so maybe we need another option..

Parameter `notation` supports `|` for multiple notations as OR, so make it OR as well, this is also the more common use case AFAIK.

**Comment by stefandesu** [comment]
> Parameter `notation` supports `|` for multiple notations as OR, so make it OR as well, this is also the more common use case AFAIK.

Makes sense! If at any point we also have a specific use case for AND, we can still implement a `mode` parameter or something. 👍

**Comment by stefandesu** [comment]
- You can now specify multiple members for lookup via `|`.
- "Not found as part of any analysis" is now shown, but only if there are no results at all. Since there might be multiple pages of results, the client can't easily determine whether one of the members has no results. The server also doesn't know, but it could in theory determine this and return it via a header. But I think that would be overkill, to be honest.

I will try to add pagination now and would close the issue afterwards.

**Comment by stefandesu** [comment]
Pagination and member lookup in ConceptDetails are now added in dev. @nichtich Please take a look and adjust the symbols if necessary.
