### ISSUE TITLE
Support backend service in addition to database

### ISSUE THREAD

**Issue by nichtich** [gbv/coli-ana#33]
Given an internal backend service to analyze DDC numbers, e.g.

    echo 704.03917104436109041074 | netcat -N esx-89.gbv.de 8080

The coli-ana web application and API should support querying this backend as fallback if no database was configured or nothing was found in the database.

**Comment by stefandesu** [comment]
A few things are required for this:
- [ ] Externalize the conversion from `convert.js` so that it can be used separately.
- [ ] Add configuration options for backend server/port.
- [ ] Integrate into API so that it falls back on a backend request if no database was configured/database is not reachable/no result was found in the database.

Question: Can we use this to analyze more than one number at a time?

**Comment by stefandesu** [comment]
Now working in https://coli-conc.gbv.de/coli-ana/dev/, but what's missing is to make it work when no database is configured at all.

**Comment by stefandesu** [comment]
We have decided to reverse the logic: Analyse numbers via the backend service by default and only use the database as a fallback. This means that we will always have the most recent analysis for each number, but if the backend service is down, we can still use the database as a fallback.
