### ISSUE TITLE
Add direct link to WebDewey

### ISSUE THREAD

**Issue by nichtich** [gbv/coli-ana#60]
A quick link into WebDewey would be very helpful but there seems to be no easy way for deep links. Maybe talk with pansoft?

**Comment by stefandesu** [comment]
What do you mean by deep links, i.e. what exactly do you want to link? Just the DDC notations? We do that in Cocoda already, so that shouldn't be a problem.

**Comment by nichtich** [comment]
Just WebDewey German and English. The problem is you need to be logged in, but that cannot be avoided.

**Comment by stefandesu** [comment]
We can add it after #50. I still don't understand why you wrote "there seems to be no easy way for deep links". Can you elaborate?

**Comment by nichtich** [comment]
> I still don't understand why you wrote "there seems to be no easy way for deep links". Can you elaborate?

Most times I used the link, I get redirected to the login form and after login, so deep links only work if you have already been logged in into WebDewey. Easy way would be if the DDC notation is passed through login form as well.

**Comment by stefandesu** [comment]
> Most times I used the link, I get redirected to the login form and after login, so deep links only work if you have already been logged in into WebDewey.

You're right, I never noticed. One option would be to not link to WebDewey directly, but rather to the DNB login form, and add the correct WebDewey link as a redirect URL. Seems to work for WebDewey German: https://services.dnb.de/dnb-cas/login?service=https%3A%2F%2Fdeweyde.pansoft.de%2Fwebdewey%2Findex_11.html%3FrecordId%3Dddc%253a612.112 (and it will automatically redirect if you're already logged in)

**Comment by stefandesu** [comment]
Another big question is: Where do we put the links? We already have three links for each line, not sure if I would want to add two more just for WebDewey links. 🤔 Or we start to use the little URI popover, because there's now a small delay and it shouldn't be as annoying.

**Comment by nichtich** [comment]
I'd keep analysis and K10plus link as icons but the third icon could open a popover with additional links and the URI

**Comment by stefandesu** [comment]
> I'd keep analysis and K10plus link as icons but the third icon could open a popover with additional links and the URI

Good idea, I'll try it out. 👍

**Comment by stefandesu** [comment]
Well, the problem is even bigger with the English WebDewey: Not only is there no obvious way to add a redirect URL to get to the correct concept, but it doesn't even remember the login session across browser tabs, it seems, so the links are completely useless. German WebDewey works well with the URL in my comment above.

**Comment by stefandesu** [comment]
I've replaced the row popover with an ellipsis and the popover now shows the URI and the German WebDewey link (we can easily add the English link if they fix the login/redirect issue - we should send them a message).

The question now is whether we should also move the Cocoda link into that popover. I haven't done it so far because I wasn't sure how to best display it if the WebDewey link is displayed via text. I do like the bird as an icon, to be honest.

**Comment by nichtich** [comment]
We could use the bird icon *instead* of the dots to open the popover just because it looks nice.

**Comment by stefandesu** [comment]
> We could use the bird icon _instead_ of the dots to open the popover just because it looks nice.

I thought that the bird could be used to link to Cocoda from other places as well though. That's what I was thinking.

**Comment by nichtich** [comment]
Then keep it as it is.
