### ISSUE TITLE
Invalid response when no notations is supplied

### ISSUE THREAD

**Issue by nichtich** [gbv/coli-ana#66]
curl https://coli-conc.gbv.de/coli-ana/dev/analyze
    [object Object]

**Comment by stefandesu** [comment]
I'm confused. First of all, if I try the same locally, I get a proper JSON response. Looking at the code, it seems like it was changed so that if no `notation` parameter is given, it does a member lookup (something that we removed from the interface some time ago), and if `search` is also not given (which is used by the lookup), it will just return the first X results from the database.

I don't know why it's different locally on my machine, and I also don't know if we still need the lookup functionality. What we could do is to only run the lookup if `notation` is empty and `search` is not empty.

**Comment by nichtich** [comment]
I have not looked at the code but in any case we can fully remove member lookup.

**Comment by stefandesu** [comment]
`curl https://coli-conc.gbv.de/coli-ana/dev/analyze` will now return an empty array.
