### ISSUE TITLE
Add script to create database and user

### ISSUE THREAD

**Issue by nichtich** [gbv/coli-ana#9]
Create a new database and user in PostgresQL.

**Comment by stefandesu** [comment]
I would rather link to the PostgreSQL docs than try to write a script for that. Sure we can keep it simple, but if half the time there's some issue and the user needs to refer to the docs anyway, we could just as well not bother.

Eventually, I would add Docker support and recommend that for hosting coli-ana since it makes everything (especially the database stuff) much easier. 

Also, how often will other people install and host this anyway?

(Docs: https://www.postgresql.org/docs/current/tutorial-createdb.html)

**Comment by nichtich** [comment]
Ok, I'll add it to the README.
